version: "3.8"

services:
  api:
    build: ./
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - ./.env
    environment:
      - ${DB_URL}:${DB_URL}
    command: uvicorn app:app --reload --host ${API_HOST} --port ${API_PORT}
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
